services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: simple-reservation-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/app:/app/app
    environment:
      - PYTHONUNBUFFERED=1